command: ["streamlit", "run", "app.py"]

env:
  - name: SUPERVISOR_AGENT_ENDPOINT
    valueFrom: serving-endpoint
  - name: GENIE_SPACE_NAME
    value: "GasEnTec LNG Operations Genie"
  - name: AI_SEARCH_INDEX
    value: "issu_dip_wksp.gasentec_hands_on.gasentec_lng_glossary_index"